export default {
  enabled: true,
  baseUrl: import.meta.env.VITE_TEXTURES_BASE_URL ?? '/media',
  preload: 'first', // 'v0', 'first' or false
  // compressionFormat: 'dds',
  compressionFormat: 'ktx',
  versions: [
    {
      cols: 512,
      rows: 104,
      width: 2048,
      height: 624,
      layers: 1,
      layerIndexStart: 0,
      // layerSrcFormat: '/low/dds/{INDEX}.dds',
      // layerSrcFormat: '/low/etc/0.etc',
      layerSrcFormat: '/low/ktx/0.ktx',
      // layerSrcFormat: '/low/dds/0.dds',
      type: 'compressed',
    },
    {
      cols: 90,
      rows: 60,
      width: 1980,
      height: 1980,
      layers: 10,
      layerIndexStart: 0,
      // layerSrcFormat: '/mid/dds/{INDEX}.dds',
      // layerSrcFormat: '/mid/etc/0.etc',
      layerSrcFormat: '/mid/ktx/0.ktx',
      // layerSrcFormat: '/mid/dds/0.dds',
      type: 'compressed',
    },
    {
      cols: 18,
      rows: 12,
      width: 1980,
      height: 1980,
      layers: 241,
      layerIndexStart: 0,
      // layerSrcFormat: '/high/dds/{INDEX}.dds',
      // layerSrcFormat: '/high/etc/0.etc',
      layerSrcFormat: '/high/ktx/0.ktx',
      // layerSrcFormat: '/high/dds/0.dds',
      type: 'compressed',
    },
  ],
}
