import mainFrag from './main.frag'

export const forceSimulationStepConfigs = {
  preview: {
    parameters: {
      // alpha: 0.15,
      // alphaTarget: 0,
      // alphaDecay: 0,
      // alphaMin: 0,
      // velocityDecay: 0.6,
    },
    forces: [
      {
        type: 'lattice',
        enabled: true,
        strength: 0.4,
        // yFactor: 1.5,
        yFactor: 3.5,
        xFactor: 1,
        // xFactor: 2,
      },
      {
        type: 'lattice',
        enabled: true,
        strength: 0.4,
        // yFactor: 1.5,
        yFactor: 3.5,
        xFactor: 1,
        reverse: true,
        // xFactor: 2,
      },
      // {
      //   type: 'lattice',
      //   enabled: true,
      //   strength: 0.8,
      //   yFactor: 1.5,
      //   xFactor: 1,
      //   reverse: true,
      //   // xFactor: 2,
      // },
      {
        type: 'origin',
        enabled: true,
        strength: 0.8,
        yFactor: 1.5,
        // strength: 0.4,
      },
      // {
      //   type: 'straightPrimaryRow',
      //   enabled: true,
      //   strength: 3.55,
      // },
      {
        type: 'push',
        enabled: true,
        // strength: 0.75,
        strength: 0.15,
        selector: 'focused',
        // yFactor: 1.5,
        // yFactor: 1.5,
        yFactor: 2.5,
        xFactor: 0.8,
        // yFactor: 1,

        // diagonalFactor: 2.55,
        // xFactor: 0.5,
        // yFactor: 1.5,
        // yFactor: 1.9,
        // yFactor: 2.9,
        // yFactor: 2,
        pointerFollow: {
          enabled: false,
          x: true,
          y: true,
          scaling: 0.25,
        },
        pointerFollowAlt: {
          enabled: false,
          x: true,
          y: true,
          scaling: 0.25,
        },
        skipYOnCenterCellRow: true,
      },
    ],
  },
  // selected: {
  //   parameters: {
  //     alpha: 0.15,
  //     alphaTarget: 0,
  //     alphaDecay: 0,
  //     alphaMin: 0,
  //     velocityDecay: 0.6,
  //   },
  //   forces: [
  //     {
  //       type: 'lattice',
  //       enabled: true,
  //       strength: 0.4,
  //       // yFactor: 1.5,
  //       yFactor: 3.5,
  //       xFactor: 1,
  //       // xFactor: 2,
  //     },
  //     {
  //       type: 'lattice',
  //       enabled: true,
  //       strength: 0.4,
  //       // yFactor: 1.5,
  //       yFactor: 3.5,
  //       xFactor: 1,
  //       reverse: true,
  //       // xFactor: 2,
  //     },
  //     // {
  //     //   type: 'lattice',
  //     //   enabled: true,
  //     //   strength: 0.8,
  //     //   yFactor: 1.5,
  //     //   xFactor: 1,
  //     //   reverse: true,
  //     //   // xFactor: 2,
  //     // },
  //     {
  //       type: 'origin',
  //       enabled: true,
  //       strength: 0.05,
  //       yFactor: 1.5,
  //       // strength: 0.4,
  //     },
  //     // {
  //     //   type: 'straightPrimaryRow',
  //     //   enabled: true,
  //     //   strength: 3.55,
  //     // },
  //     {
  //       type: 'push',
  //       enabled: true,
  //       // strength: 0.75,
  //       strength: 0.15,
  //       selector: 'focused',
  //       // yFactor: 1.5,
  //       // yFactor: 1.5,
  //       yFactor: 2.5,
  //       xFactor: 0.8,
  //       // yFactor: 1,
  //
  //       // diagonalFactor: 2.55,
  //       // xFactor: 0.5,
  //       // yFactor: 1.5,
  //       // yFactor: 1.9,
  //       // yFactor: 2.9,
  //       // yFactor: 2,
  //       pointerFollow: {
  //         enabled: false,
  //         x: true,
  //         y: true,
  //         scaling: 0.25,
  //       },
  //       pointerFollowAlt: {
  //         enabled: false,
  //         x: true,
  //         y: true,
  //         scaling: 0.25,
  //       },
  //       skipYOnCenterCellRow: true,
  //     },
  //   ],
  // },
  select: {
    parameters: {
      // alpha: 0.35,
      // alphaTarget: 0,
      // alphaDecay: 0,
      // alphaMin: 0,
      velocityDecay: 0.5,
    },
    forces: [
      {
        type: 'lattice',
        enabled: true,
        strength: 0.4,
        // yFactor: 1.5,
        yFactor: 1.5,
        xFactor: 1,
        // xFactor: 2,
      },
      {
        type: 'lattice',
        enabled: true,
        strength: 0.4,
        // yFactor: 1.5,
        yFactor: 1.5,
        xFactor: 1,
        reverse: true,
        // xFactor: 2,
      },
      // {
      //   type: 'lattice',
      //   enabled: true,
      //   strength: 0.8,
      //   yFactor: 1.5,
      //   xFactor: 1,
      //   reverse: true,
      //   // xFactor: 2,
      // },
      {
        type: 'origin',
        enabled: true,
        strength: 0.1,
        // yFactor: 1.5,
      },
      {
        type: 'push',
        enabled: true,
        // strength: 0.75,
        strength: 0.15,
        yFactor: 1.5,
        // xFactor: 0.8,
        selector: 'focused',
        pointerFollow: {
          enabled: false,
          x: true,
          y: true,
          scaling: 0.25,
        },
        pointerFollowAlt: {
          enabled: false,
          x: true,
          y: true,
          scaling: 0.25,
        },
        skipYOnCenterCellRow: true,
        // diagonalFactor: 1.45,
      },
    ],
  },
}
export default {
  devTools: {
    enabled: false,
    expanded: false,
  },
  // idlePointerMode: false,
  cells: 50000,
  // cells: 5000,

  media: {
    enabled: true,
    baseUrl: import.meta.env.VITE_TEXTURES_BASE_URL ?? '/media',
    versions: [
      {
        cols: 512,
        rows: 288,
        width: 2048,
        height: 624,
        layers: 1,
        layerIndexStart: 0,
        layerSrcFormat: '/low/dds/{INDEX}.dds',
      },
      {
        cols: 90,
        rows: 60,
        width: 1980,
        height: 1980,
        layers: 6,
        layerIndexStart: 0,
        layerSrcFormat: '/mid/dds/{INDEX}.dds',
      },
      {
        cols: 18,
        rows: 12,
        width: 1980,
        height: 1980,
        layers: 141,
        layerIndexStart: 0,
        layerSrcFormat: '/high/dds/{INDEX}.dds',
      },
    ],
  },
  multiThreading: {
    enabled: true,
    renderInParallel: true,
  },
  lattice: {
    mode: 'default',
  },
  controls: {
    autoFocusCenter: {
      enabled: true,
      random: false,
    },
    maxPointerSpeed: 1250, // px/s
  },
  display: {
    scene: {
      dev: {
        enabled: false,
      },
      main: {
        // enabled: false,
        fragmentShader: mainFrag,
        uniforms: {},
      },
    },
    renderer: {
      scissor: {
        enabled: true,
        offset: {
          top: 0,
          right: 0,
          bottom: 0,
          // left: 100,
        },
      },
    },
  },
  simulation: {
    steps: {
      voronoi: {
        latticeNeighborLevels: 3,
        // baseFocusedWeight: 1,
        // baseFocusedDirectXNeighborWeight: 0.25,
        // baseFocusedWeight: 2.75,
        baseFocusedWeight: 0,
        // baseFocusedDirectXNeighborWeight: 0.5,
        baseFocusedDirectXNeighborWeight: 0,
      },
      force: forceSimulationStepConfigs.preview,
    },
  },
}
